# Site settings
title: The Roaming Ginger
header-img: img/home-bg.jpg
email: georgebonnicicarter@gmail.com
copyright_name: Roaming Ginger
description: "My experience throughtout the world and technology"
baseurl: ""
url: "http://.com"
# twitter_username: SBootstrap
github_username:  GeorgeB123
facebook_username:  georgebonnici-carter
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]


# Where things are
source:      .
destination: ./_site
layouts:     ./_layouts
# data_source: ./_data
collections: null
future: true

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
